// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250522130800_Add Models")]
    partial class AddModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Models.Calculator", b =>
                {
                    b.Property<int>("CalculatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalculatorId"));

                    b.Property<DateTime>("DateOfCalculation")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Number1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Number2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Result")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CalculatorId");

                    b.ToTable("Calculators");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Parallelogram", b =>
                {
                    b.Property<int>("ParallelogramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParallelogramId"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Base")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Circumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("DateOfCalculation")
                        .HasColumnType("date");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsRhombus")
                        .HasColumnType("bit");

                    b.Property<decimal>("Side")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ParallelogramId");

                    b.ToTable("Parallelograms");
                });

            modelBuilder.Entity("DataAccessLayer.Models.RectangleModel", b =>
                {
                    b.Property<int>("RectangleModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RectangleModelId"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Base")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Circumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("DateOfCalculation")
                        .HasColumnType("date");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RectangleModelId");

                    b.ToTable("RectangleModels");
                });

            modelBuilder.Entity("DataAccessLayer.Models.RockPaperScissor", b =>
                {
                    b.Property<int>("RockPaperScissorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RockPaperScissorId"));

                    b.Property<string>("ComputerHand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfGame")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GamesWonAverage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlayerHand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RockPaperScissorId");

                    b.ToTable("RockPaperScissors");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Triangle", b =>
                {
                    b.Property<int>("TriangleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TriangleId"));

                    b.Property<decimal>("Area")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Base")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Circumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("DateOfCalculation")
                        .HasColumnType("date");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SideA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SideB")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SideC")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TriangleId");

                    b.ToTable("Triangles");
                });
#pragma warning restore 612, 618
        }
    }
}
